name = "Tissue"
uuid = "d793e989-9861-40a6-8a6f-c6c683623071"
authors = ["Philippe Laferriere <laferriere.phil@gmail.com> and contributors"]
version = "0.2.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
